### ISSUE TITLE
シラサギのスタートアップスクリプトを改修したい

### ISSUE THREAD

**Issue by hourin** [sakura-internet/cloud-startupscripts#72]
以前にシラサギのスタートアップスクリプトを作成しました。
https://github.com/sakura-internet/cloud-startupscripts/blob/master/publicscript/shirasagi/shirasagi.sh
その後、スタートアップスクリプトから呼び出しているシラサギのインストールプログラムが更新され、管理画面のポート番号が3000番から80番に変わりました。
そこで、それに対応してスタートアップスクリプトを改修したいです。

#   http://IPアドレス:3000/.mypage
↓
#   http://IPアドレス/.mypage

#---------START OF firewalld---------#
# シラサギの管理画面は3000番ポートを使用するため、
# サーバに対して3000番ポートでアクセスできるようにします。
firewall-cmd --permanent --add-port=3000/tcp
firewall-cmd --reload
#---------END OF firewalld---------#
↓
削除

プルリクエストを出そうと思ったのですが、不慣れなので変なことをしそうなのと、来週にはこれを使ったチュートリアルが公開される予定なのでそれまでに改修したいという事情があり、変更をお願いできませんでしょうか。すみませんがよろしくお願いします。

**Comment by zakinko** [comment]
@zembutsu プルリクありがとうございます。
@hourin こちらマージが完了しましたのでクローズさせていただきます。
